# Generated by Django 3.2.6 on 2021-08-27 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name_student', error_messages={'unique': 'ياباشا بطل عبط'}, help_text='Enter Your Name hier', max_length=40, null=True, unique=True, verbose_name='Name Student')),
                ('age', models.BigIntegerField(default=12, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('fmale', 'fmale'), ('other', 'other')], max_length=10, null=True)),
                ('agree', models.BooleanField(null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('emil', models.EmailField(max_length=100, null=True)),
                ('Teacher_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
        ),
    ]
