# Generated by Django 3.2.6 on 2021-08-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fach'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Fach_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fach'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Teacher_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
    ]
