# Generated by Django 3.2.6 on 2021-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210827_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Book',
            field=models.ManyToManyField(to='myapp.Library'),
        ),
    ]
