# Generated by Django 3.2.6 on 2021-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_father'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father',
            options={'verbose_name': 'Father_Rena'},
        ),
        migrations.AlterField(
            model_name='father',
            name='name',
            field=models.CharField(db_column='namex', max_length=20, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='father',
            table='Father_T',
        ),
    ]
