# Generated by Django 3.2.6 on 2021-08-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210828_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father',
            options={'ordering': ['name']},
        ),
    ]
