# Generated by Django 3.2.6 on 2021-08-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_father_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father',
            options={'ordering': ['age']},
        ),
    ]
