# Generated by Django 3.2.6 on 2021-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_book_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='fach',
            name='Price',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
    ]
