# Generated by Django 3.2.6 on 2021-09-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_fach_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fach',
            old_name='Price',
            new_name='price',
        ),
    ]
